### ISSUE TITLE
Pantheon: Why Local Development Makes Better Development Case Study

### ISSUE THREAD

**Issue by pirog** [kalabox/tandem#32]

**Comment by reynoldsalec** [comment]
**Proposed Takeaways**
- If you're a hosting provider, hire us to make an integration
  -- If you're looking for an expert in local development

Why your hosting platform needs a local development solution
Why develop locally

**Future Pantheon-related Articles**
- If you're looking for Docker infrastructure, hire us because we can create complex environments like Pantheon's
- If you're looking for automated testing, hire us because we can integrate it in a workflow that deploys to Pantheon or a different hosting provider

**Proposed Titles**
- Case Study: Solving Local Development for the Pantheon Platform
- Case Study: Emulating the Pantheon Platform with Docker
- Case Study: Putting the Pantheon Platform on Your Computer with Docker
- **Docker-based Local Development: The Pantheon Platform on Kalabox**
- Docker-based Local Development: Putting the Pantheon Platform on Your Computer

**Outline**
- Introduce the Problem:
  - Who is Pantheon?
  - Pantheon's problem: they want more agencies to standardize on their platform
  - How do I get a developer from nothing to contributing code on Pantheon with the greatest confidence their code will work on the platform? === Great developer experience.
- Sketch out the solution
  - Kalabox provided a self-contained package
  - Advantage: as an open-source project, Pantheon doesn't have to dedicate resources and benefits from a wider community beyond Pantheon
- Production Parity
  - How Docker makes this possible
  - Provides Pantheon's CLI tools
- Integrates with their API
  - Makes local a part of the Pantheon workflow
- Conclusion: Emphasize the before/after picture
  - Show how quickly onboarding a new dev can go (compared to the pre-Kalabox world)

**Comment by reynoldsalec** [comment]
We should repost my Pantheon blog post on our site.
